# Generated by Django 3.1 on 2021-04-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
