# Generated by Django 3.1 on 2021-04-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210404_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='timesTamp',
            new_name='timestamp',
        ),
    ]
