# Generated by Django 3.1 on 2021-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210404_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='timestamp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
